config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  # PostsController
  get '/', to: 'posts#index', as: 'index_post'
  get 'posts/new', to: 'posts#new', as: 'new_post'
  get 'topics/new', to: 'topics#new'
  get 'topics/edit', to: 'topics#edit', as: 'edit_topics'
  
  post 'posts/new', to: 'posts#create', as: 'create_post'
  
  # TopicsController
  get 'topics/new', to: 'topics#new', as: 'new_topic'
  post 'topics/new', to: 'topics#create', as: 'create_topics'
  get 'topics/edit/:id', to: 'topics#edit', as: 'edit_topic'
  post 'topics/edit', to: 'topics#update', as: 'update_topics'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/post.rb
class Post < ApplicationRecord
     #Validation
     validates :title, presence: true
     validates :body, presence: true
     
     #ActiveStorage
     has_one_attached :image
     
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    
    before_action :authenticate_user!
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    before_action :authenticate_user!

    def index
        render 'posts/index'
    end
    
    #ここから
    def new
      @post = Post.new
      render :new
    end 
    
    def create
      @post = Post.new(post_params)
      
      if params[:post][:image]
          @post.image.attach(params[:post][:image])
      end
      
      if @post.save
          redirect_to index_post_path, notice: '登録しました'
      else
          render :new, status: :unprocessable_entity
      end
    end
    
    private
    def post_params
      params.require(:post).permit(:title, :body, :image)
    end
    #ここまで
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
    def new
        render :new
    end 
    
    def create 
        redirect_to 'topics/new'
    end
    
    def edit
        render
    end 
    
    def update
        redirect_to 'topics/edit'
    end 
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/laravel_mix_helper.rb
module LaravelMixHelper
  class LaravelMixError < StandardError; end
  MANIFEST_FILE = 'public/mix-manifest.json'

  def mix(path)
    unless File.exist?(MANIFEST_FILE)
      raise LaravelMixError, "The Mix manifest does not exist at #{MANIFEST_FILE}. Run `yarn run dev`."
    end

    manifest = JSON.parse(File.read(MANIFEST_FILE))
    asset_path(manifest.fetch(path) { raise LaravelMixError, "No asset found for #{path} in the Mix manifest." })
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="ja">
  <head>

    <title>SNS App</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="<%= mix('/css/app.css') %>">
 
    <script src="<%= mix('/js/bootstrap.js') %>"></script>
    
    <script src="<%= mix('/js/turbo.js') %>"></script>
  </head>

  <body>
    <div class="main-container">
    
      <nav class="custom-navbar">
        <div id="menuToggle">
          <input type="checkbox" />
          <span></span>
          <span></span>
          <span></span>
          <ul id="menu">
            
            <% if user_signed_in? %>
              <!--ログインしている場合に表示されます-->
              <!--user_signed_in?はdeviceが提供している認証済みかを判定するメソッドです-->
            <li>
              <%= link_to "ログアウト", destroy_user_session_path, method: :delete,class: "nav-link" %>
            </li>
            
            <li>
              <%= link_to "投稿一覧", "/", class: "nav-link" %>
            </li>
            
            <li>
              <%= link_to "新規投稿", new_post_path, class: "new-link" %>
            </li>
          <% else %>
              <!--ログインしていない場合に表示されます-->
              <!--else以降は前述のif文の否定になります-->  
              
            <li>
              <%= link_to "新規登録", new_user_registration_path, class: "nav-link" %>
            </li>
            
             <li>
              <%= link_to "ログイン", new_user_session_path, class: "nav-link" %>
            </li>
          <% end %>
              
          </ul>
        </div>
      </nav>

      <!-- アラートメッセージ -->
      <% if notice %>
        <div class="alert alert-success" role="alert">
          <%= notice %>
        </div>
      <% end %>
      <% if alert %>
        <div class="alert alert-danger" role="alert">
          <%= alert %>
        </div>
      <% end %>

      <div class="bg-white text-dark">
        <%= yield %>
      </div>
    </div>

    <!-- Javascript追加 -->
    <script src="<%= mix('/js/app.js') %>"></script>
  </body>
</html>

app/views/posts/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-8 mx-auto post-form-container">
      <h2 class="h2">投稿編集</h2>
      <%= form_with(url: update_post_path,model: @post, local: true, method: :post,html: {class:'post-form'}) do |f| %>
      
      <% if @post.errors.any? %>
      <ul>
        <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
        <% end %></ul>
      <% end %>
      
      <div class="form-group">
        <%= f.label"タイトル", class: 'form-label' %>
        <%= f.text_field :title, value: @post.title, class:'form-control' %>
      </div>
      
      <div class="form-group">
        <%= f.label"本文", class: 'form-label' %>
        <%= f.text_area :body, value: @post.body, class:'form-control' %>
      </div>
  
      <div class="form-group image-upload">
        <%= f.label "画像", class: 'form-label' %>
        <div class="image-preview" id="imagePreview">
          <img src="<%= @post.image.attached? ? url_for(@post.image) : "" %>" alt="Image Preview" class="image-preview__image <%= @post.image.attached? ? "-block" : "" %>">
          <span class="image-preview__default-text <%= @post.image.attached? ? "-none" : "" %>">No image uploaded</span>
        </div>
        <%= f.file_field :image, class: 'form-control-file', id: 'imageUpload' %>
      </div>
      
      <div class="button-group"> 
      
      
      <%= link_to '削除', destroy_post_path(@post), method: :delete, data: {confirm: '本当に削除しますか?' }, class: "btn btn-danger" %>
      <%= f.submit '更新', class: 'btn btn-primary' %>
      </div>
    <% end %>
      
    </div>
    
  </div>
  
</di

app/views/posts/index.html.erb
<div class="search-container">
    <%= form_with url: index_post_path, class:"form",method: :get, local: true do |form| %>
    <input class="input" type="text" name="title" placeholder="タイトルで検索" value="<%= params[:title] %>">
    <%= form.submit"検索",class: "button" %>
   <% end %>
</div>

app/views/posts/index2.html.erb
<div class="search-container">
    <%= form_with url: index_post_path, class:"form",method: :get, local: true do |form| %>
    <input class="input" type="text" name="title" placeholder="タイトルで検索" value="<%= params[:title] %>">
    <%= form.submit"検索",class: "button" %>
   <% end %>
</div>

=begin

<div class="post-list">
    <% @posts.each do |post| %>
    
    <a class="post" href="<%= new_comment_path(post) %>">
        <div class="header">
            <h2 class="title"><%= post.title %> </h2>
            <p class="timestamp"><%= post.created_at.strftime("%B %d, %Y") %></p>
        </div>
        <div class="body">
            <p class="content"><%= post.body %></p>
        </div>
        <div class="image">
            <%= image_tag(post.image) if post.image.attached? %>
        </div>
    </a>
    <% end %>
</div>

=end

app/views/posts/new.html.erb
<div>
    <h1>スレッド新規登録</h1>
</div>
<div class="container">
  <div class="row">
    <div class="col-md-8 mx-auto post-form-container">
      <h2> 新規投稿</h2>
      <!--ここから入れ替えて追加します-->
      <!--model: @postを追加しています-->
      <%= form_with(url: create_post_path, local: true, method: :post, html: { class:'post-form' } ) do |f| %>
      <!--バリデーションエラーメッセージ表示を追加しています-->
      <% if @post.errors.any? %>
       <ul>
           <% @post.errors.full_messages.each do |message| %>
             <li>< message %></li>
           <% end %></ul>
      <% end %>
       <!--ここまで-->
       <div class="form-group">
           <%= f.label "タイトル", class: 'form-label' %>
           <%= f.text_field :title, class: 'form-control' %>
       </div>
       
       <div class="form-group">
           <%= f.label "本文", class: 'form-label' %>
           <%= f.text_area :body, class: 'form-control' %>
       </div>
       
       <div class="form-group image-upload">
            <%= f.label "画像", class: 'form-label' %>
            <div class="image-preview" id="imagePreview">
                <img src="" alt="Image Preview" class="image-preview_image">
                <span class="image-preview_default-text">Image will be displayed here</span>
            </div>
            <%= f.file_field :image, class: 'form-control-file', id: 'imageUpload' %>
       </div>
       
       <div class="button-group">
           <%= f.submit "投稿する", class: 'btn btn-primary' %>
       </div>
     <% end %>
     </div>
    </div> 
 </div>